/** @type {import("./data").Project[]} */
export const projects = [
  {
    id: "prj_01",
    name: "Manauary Reforestation Corridor",
    producerId: "prd_01",
    registry: "Verra",
    projectId: "VCS-9341",
    category: "Reforestation",
    location: "Amazon Basin, Brazil",
    coords: { lat: -3.4653, lon: -62.2159 },
    description:
      "Restoring 12,400 hectares of primary rainforest corridor in partnership with three indigenous communities. Sequentially monitored through satellite dMRV and ground sensors.",
    imageHue: "142 76% 36%",
    totalIssued: 18_200,
    totalRetired: 6_100,
    available: 12_100,
    pricePerTonne: 18.4,
    vintage: "2024",
    status: "Active",
    sensorIds: ["sns_01", "sns_02", "sns_03"],
    createdAt: "2024-03-12",
    methodologyDoc: "VM0007 v1.6 — Avoided Ecosystem Conversion",
  },
  {
    id: "prj_02",
    name: "Mammoth Direct Air Capture",
    producerId: "prd_02",
    registry: "Verra",
    projectId: "VCS-2128",
    category: "Direct Air Capture",
    location: "Hellisheidi, Iceland",
    coords: { lat: 64.0466, lon: -21.4126 },
    description:
      "Geothermal-powered solid sorbent DAC facility capturing 36,000 tCO₂ annually. Mineralized basalt injection provides 10,000+ year sequestration.",
    imageHue: "187 86% 43%",
    totalIssued: 38_120,
    totalRetired: 22_400,
    available: 15_720,
    pricePerTonne: 412.0,
    vintage: "2025",
    status: "Active",
    sensorIds: ["sns_04", "sns_05"],
    createdAt: "2023-09-04",
    methodologyDoc: "Puro.earth Geologically Stored Carbon",
  },
  {
    id: "prj_03",
    name: "Coral Triangle Mangrove Network",
    producerId: "prd_03",
    registry: "Gold Standard",
    projectId: "GS-8832",
    category: "Blue Carbon",
    location: "Raja Ampat, Indonesia",
    coords: { lat: -0.2286, lon: 130.5167 },
    description:
      "Community-led mangrove restoration across 2,300 hectares. Verified through quarterly biomass sampling and Sentinel-2 satellite change detection.",
    imageHue: "160 84% 39%",
    totalIssued: 12_800,
    totalRetired: 4_200,
    available: 8_600,
    pricePerTonne: 24.7,
    vintage: "2024",
    status: "Active",
    sensorIds: ["sns_06", "sns_07"],
    createdAt: "2024-07-22",
    methodologyDoc: "VM0033 v2.0 — Tidal Wetland and Seagrass Restoration",
  },
  {
    id: "prj_04",
    name: "Imperial Valley Methane Recovery",
    producerId: "prd_04",
    registry: "CAR",
    projectId: "CAR-1247",
    category: "Methane Capture",
    location: "California, USA",
    coords: { lat: 32.8475, lon: -115.5694 },
    description:
      "Capturing methane from dairy operations across 14 farms. Gas is scrubbed and injected into the pipeline, displacing fossil fuel-derived natural gas.",
    imageHue: "38 92% 50%",
    totalIssued: 18_200,
    totalRetired: 9_800,
    available: 8_400,
    pricePerTonne: 31.5,
    vintage: "2025",
    status: "Listed",
    sensorIds: ["sns_08"],
    createdAt: "2024-01-18",
    methodologyDoc: "AMS-III.H — Methane Recovery in Animal Manure Management",
  },
  {
    id: "prj_05",
    name: "Sahel Regenerative Soils",
    producerId: "prd_05",
    registry: "Gold Standard",
    projectId: "GS-5544",
    category: "Soil Sequestration",
    location: "Kaolack Region, Senegal",
    coords: { lat: 14.1592, lon: -16.0718 },
    description:
      "Farmer cooperative regenerating degraded soils across 8,200 hectares using cover cropping, compost teas, and rotational grazing.",
    imageHue: "350 89% 60%",
    totalIssued: 6_400,
    totalRetired: 1_200,
    available: 5_200,
    pricePerTonne: 16.2,
    vintage: "2024",
    status: "Active",
    sensorIds: ["sns_09", "sns_10"],
    createdAt: "2025-02-08",
    methodologyDoc: "VM0042 v1.0 — Improved Agricultural Land Management",
  },
  {
    id: "prj_06",
    name: "Atacama Solar Thermal Array",
    producerId: "prd_01",
    registry: "Verra",
    projectId: "VCS-7715",
    category: "Renewable Energy",
    location: "Antofagasta, Chile",
    coords: { lat: -23.6509, lon: -70.3975 },
    description:
      "210 MW concentrated solar thermal plant displacing coal-fired generation. Connected to the SEN grid with hourly production telemetry.",
    imageHue: "262 83% 58%",
    totalIssued: 42_600,
    totalRetired: 18_300,
    available: 24_300,
    pricePerTonne: 8.4,
    vintage: "2025",
    status: "Active",
    sensorIds: ["sns_11"],
    createdAt: "2024-08-30",
    methodologyDoc: "ACM0002 — Grid-connected Renewable Generation",
  },
];
